## Color palette

# yellows:  dba355 d8a038 d8bd36 edd17d
# greens:   92ef92 6bbf3b 1cef5c 75b72d 9fea8f c6e84e c1f45a b8d613 fcf0b5 
# reds:     dd362a
# blues:    5b91c6 2a7d93 0bb1ed
# pinks:    bf0f73
# oranges:  ba500e ce8048
# teals:    40c491

###
### Areas
#
- name: area/conn-manager
  color: 0bb1ed
  description: "Area: Connection Manager"
- name: area/connection-bootstrapping
  color: 0bb1ed
  description: "Area: Connection Bootstrapping"
- name: area/nat-traversal
  color: 0bb1ed
  description: "Area: NAT Traversal"
- name: area/peer-routing
  color: 0bb1ed
  description: "Area: Peer Routing"
- name: area/content-routing
  color: 0bb1ed
  description: "Area: Content Routing"
- name: area/discovery
  color: 0bb1ed
  description: "Area: Discovery"
- name: area/identity
  color: 0bb1ed
  description: "Area: Identity"
- name: area/multiplexing
  color: 0bb1ed
  description: "Area: Multiplexing"
- name: area/negotiation
  color: 0bb1ed
  description: "Area: Negotiation"
- name: area/peerstore
  color: 0bb1ed
  description: "Area: Peerstore"
- name: area/pubsub
  color: 0bb1ed
  description: "Area: Pubsub"
- name: area/circuit-relay
  color: 0bb1ed
  description: "Area: Circuit Relay"
- name: area/secure-channel
  color: 0bb1ed
  description: "Area: Secure Channel"
- name: area/transport
  color: 0bb1ed
  description: "Area: Transport"
- name: area/general
  color: 0bb1ed
  description: "Area: General"  

###
### Components
#
- name: comp/floodsub
  color: edd17d
  description: "Component: Floodsub"
- name: comp/gossipsub
  color: edd17d
  description: "Component: Gossipsub"
- name: comp/kad-dht
  color: edd17d
  description: "Component: Kademlia DHT"
- name: comp/noise
  color: edd17d
  description: "Component: Noise"
- name: comp/quic
  color: edd17d
  description: "Component: QUIC"
- name: comp/secio
  color: edd17d
  description: "Component: SecIO"
- name: comp/tcp
  color: edd17d
  description: "Component: TCP"
- name: comp/tls
  color: edd17d
  description: "Component: TLS"
- name: comp/webrtc
  color: edd17d
  description: "Component: WebRTC"
- name: comp/websockets
  color: edd17d
  description: "Component: WebSockets"
- name: comp/yamux
  color: edd17d
  description: "Component: Yamux"  

###
### Kinds
#
- name: kind/bug
  color: c92712
  description: "Kind: Bug"
- name: kind/improvement
  color: fcf0b5
  description: "Kind: Improvement"
- name: kind/test
  color: fcf0b5
  description: "Kind: Test"
- name: kind/tracking-issue
  color: fcf0b5
  description: "Kind: Tracking Issue"
- name: kind/question
  color: fcf0b5
  description: "Kind: Question"
- name: kind/enhancement
  color: fcf0b5
  description: "Kind: Enhancement"
- name: kind/discussion
  color: fcf0b5
  description: "Kind: Discussion"  

###
### Difficulties
#
- name: dif/trivial
  color: b2b7ff
  description: "Can be confidently tackled by newcomers, who are widely unfamiliar with libp2p."
- name: dif/easy
  color: 7886d7
  description: "A prexisting libp2p user should be able to pick this up."
- name: dif/medium
  color: 6574cd
  description: "Prior experience in having developed libp2p modules is likely helpful."
- name: dif/hard
  color: 5661b3
  description: "Suggests that having worked on the specific component affected by this issue is important."
- name: dif/expert
  color: 2f365f
  description: "Requires extensive knowledge of the history, implications, ramifications of the issue."  

###
### Efforts
#
- name: effort/minutes
  color: e8fffe
  description: "Effort: Minutes"
- name: effort/hours
  color: a0f0ed
  description: "Effort: One or Multiple Hours."
- name: effort/day
  color: 64d5ca
  description: "Effort: One Day."
- name: effort/days
  color: 4dc0b5
  description: "Effort: Multiple Days."
- name: effort/week
  color: 38a89d
  description: "Effort: One Week."
- name: effort/weeks
  color: 20504f
  description: "Effort: Multiple Weeks."  

###
### Impacts
#
- name: impact/regression
  color: f1f5f8
  description: "Impact: Regression"
- name: impact/api-breakage
  color: f1f5f8
  description: "Impact: API Breakage"
- name: impact/quality
  color: f1f5f8
  description: "Impact: Quality"
- name: impact/dx
  color: f1f5f8
  description: "Impact: Developer Experience"
- name: impact/test-flakiness
  color: f1f5f8
  description: "Impact: Test Flakiness"  

###
### Topics
#
- name: topic/interoperability
  color: bf0f73
  description: "Topic: Interoperability"
- name: topic/docs
  color: bf0f73
  description: "Topic: Documentation"
- name: topic/infra
  color: bf0f73
  description: "Topic: Infrastructure"
- name: topic/architecture
  color: bf0f73
  description: "Topic: Architecture"  

###
### Priorities
###
- name: P0
  color: dd362a
  description: "P0: Critical. This is a blocker. Drop everything else."
- name: P1
  color: ce8048
  description: "P1: Must be fixed."
- name: P2
  color: dbd81a
  description: "P2: Should be fixed."
- name: P3
  color: 9fea8f
  description: "P3: Might get fixed."

###
### Hints
#
- name: hint/good-first-issue
  color: 0623cc
  description: "Hint: Good First Issue"
- name: hint/needs-contributor
  color: 0623cc
  description: "Hint: Needs Contributor"
- name: hint/needs-participation
  color: 0623cc
  description: "Hint: Needs Participation"
- name: hint/needs-decision
  color: 0623cc
  description: "Hint: Needs Decision"
- name: hint/needs-triage
  color: 0623cc
  description: "Hint: Needs Triage"
- name: hint/needs-analysis
  color: 0623cc
  description: "Hint: Needs Analysis"
- name: hint/needs-author-input
  color: 0623cc
  description: "Hint: Needs Author Input"
- name: hint/needs-team-input
  color: 0623cc
  description: "Hint: Needs Team Input"
- name: hint/needs-community-input
  color: 0623cc
  description: "Hint: Needs Community Input"
- name: hint/needs-review
  color: 0623cc
  description: "Hint: Needs Review"
- name: hint/needs-help
  color: 0623cc
  description: "Hint: Needs Help"  

###
### Statuses
#
- name: status/done
  color: edb3a6
  description: "Status: Done"
- name: status/deferred
  color: edb3a6
  description: "Status: Deferred"
- name: status/in-progress
  color: edb3a6
  description: "Status: In Progress"
- name: status/blocked
  color: edb3a6
  description: "Status: Blocked"
- name: status/inactive
  color: edb3a6
  description: "Status: Inactive"
- name: status/waiting
  color: edb3a6
  description: "Status: Waiting"
- name: status/rotten
  color: edb3a6
  description: "Status: Rotten"  
