## Color palette

# yellows:  c6e84e c1f45a b8d613 fcf0b5
# greens:   92ef92 6bbf3b 1cef5c 75b72d 9fea8f
# reds:     dd362a
# blues:    5b91c6 2a7d93 0bb1ed
# pinks:    bf0f73
# oranges:  ba500e ce8048
# teals:    40c491

###
### Areas
###
- color: 2a7d93
  name: area/conn-manager
- color: 2a7d93
  name: area/connection-bootstrapping
- color: 2a7d93
  name: area/nat-traversal
- color: 2a7d93
  name: area/peer-routing
- color: 2a7d93
  name: area/content-routing
- color: 2a7d93
  name: area/discovery
- color: 2a7d93
  name: area/identity
- color: 2a7d93
  name: area/multiplexing
- color: 2a7d93
  name: area/negotiation
- color: 2a7d93
  name: area/peerstore
- color: 2a7d93
  name: area/pubsub
- color: 2a7d93
  name: area/relay
- color: 2a7d93
  name: area/security-channel
- color: 2a7d93
  name: area/transport
- color: 2a7d93
  name: area/universal

###
### Components
###
- color: fcf0b5
  name: comp/floodsub
- color: fcf0b5
  name: comp/gossipsub
- color: fcf0b5
  name: comp/kad-dht
- color: fcf0b5
  name: comp/noise
- color: fcf0b5
  name: comp/quic
- color: fcf0b5
  name: comp/secio
- color: fcf0b5
  name: comp/tcp
- color: fcf0b5
  name: comp/tls
- color: fcf0b5
  name: comp/webrtc
- color: fcf0b5
  name: comp/wss
- color: fcf0b5
  name: comp/yamux

###
### Kinds
###
- color: c92712
  name: kind/bug
- color: 97f4ca
  name: kind/improvement
- color: 97f4ca
  name: kind/test
- color: 97f4ca
  name: kind/tracking-issue
- color: 97f4ca
  name: kind/question
- color: 97f4ca
  name: kind/enhancement
- color: 97f4ca
  name: kind/architecture
- color: 97f4ca
  name: kind/discussion

###
### Difficulties
###
- color: b2b7ff
  name: dif/trivial
- color: 7886d7
  name: dif/easy
- color: 6574cd
  name: dif/medium
- color: 5661b3
  name: dif/hard
- color: 2f365f
  name: dif/expert

###
### Efforts
###
- color: e8fffe
  name: effort/minutes
- color: a0f0ed
  name: effort/hours
- color: 64d5ca
  name: effort/day
- color: 4dc0b5
  name: effort/days
- color: 38a89d
  name: effort/week
- color: 20504f
  name: effort/weeks

###
### Impacts
###
- color: 3222c9
  name: impact/regression
- color: 3222c9
  name: impact/api-breakage
- color: 3222c9
  name: impact/quality
- color: 3222c9
  name: impact/dx
- color: 3222c9
  name: impact/test-flakiness

###
### Topics
###
- color: bf0f73
  name: topic/interoperability
- color: bf0f73
  name: topic/docs
- color: bf0f73
  name: topic/infra

###
### Priorities
###
- color: dd362a
  name: P0
- color: ce8048
  name: P1
- color: dbd81a
  name: P2
- color: 9fea8f
  name: P3

###
### Hints
###
- color: 0623cc
  name: hint/good-first-issue
- color: 0623cc
  name: hint/needs-contributor
- color: 0623cc
  name: hint/needs-participation
- color: 0623cc
  name: hint/needs-decision
- color: 0623cc
  name: hint/needs-triage
- color: 0623cc
  name: hint/needs-analysis
- color: 0623cc
  name: hint/needs-author-input
- color: 0623cc
  name: hint/needs-team-input
- color: 0623cc
  name: hint/needs-community-input
- color: 0623cc
  name: hint/needs-review
- color: 0623cc
  name: hint/needs-help

###
### Statuses
###
- color: eab7f7
  name: status/done
- color: eab7f7
  name: status/deferred
- color: eab7f7
  name: status/in-progress
- color: eab7f7
  name: status/blocked
- color: eab7f7
  name: status/inactive
- color: eab7f7
  name: status/waiting
- color: eab7f7
  name: status/rotten
