## Colors
#c6e84e #c1f45a #b8d613 yellow
#92ef92 green
#dd362a red
#5b91c6 off blue
#2a7d93 darkish blue
#fcf0b5 wheat
# XX 0bb1ed bright blue
#ba500e #ce8048 orange
#6bbf3b 1cef5c bright green
#bf0f73 bright pink
#75b72d green
#40c491 teal
#9fea8f light green

###
### Areas
###
- color: 2a7d93
  name: area/conn-manager
- color: 2a7d93
  name: area/connection-bootstrapping
- color: 2a7d93
  name: area/nat-traversal
- color: 2a7d93
  name: area/peer-routing
- color: 2a7d93
  name: area/content-routing
- color: 2a7d93
  name: area/discovery
- color: 2a7d93
  name: area/identity
- color: 2a7d93
  name: area/multiplexing
- color: 2a7d93
  name: area/negotiation
- color: 2a7d93
  name: area/peerstore
- color: 2a7d93
  name: area/pubsub
- color: 2a7d93
  name: area/relay
- color: 2a7d93
  name: area/security-channel
- color: 2a7d93
  name: area/transport
- color: 2a7d93
  name: area/universal

###
### Components
###
- color: fcf0b5
  name: comp/floodsub
- color: fcf0b5
  name: comp/gossipsub
- color: fcf0b5
  name: comp/kad-dht
- color: fcf0b5
  name: comp/noise
- color: fcf0b5
  name: comp/quic
- color: fcf0b5
  name: comp/secio
- color: fcf0b5
  name: comp/tcp
- color: fcf0b5
  name: comp/tls
- color: fcf0b5
  name: comp/webrtc
- color: fcf0b5
  name: comp/wss
- color: fcf0b5
  name: comp/yamux

###
### Kinds
###
- color: ea1e62
  name: kind/bug
- color: 000000
  name: kind/improvement
- color: 000000
  name: kind/test
- color: 000000
  name: kind/tracking-issue
- color: 000000
  name: kind/question
- color: 000000
  name: kind/enhancement
- color: 000000
  name: kind/architecture
- color: 000000
  name: kind/discussion

###
### Difficulties
###
- color: 000000
  name: dif/trivial
- color: 000000
  name: dif/easy
- color: 000000
  name: dif/medium
- color: 000000
  name: dif/hard
- color: 000000
  name: dif/expert

###
### Efforts
###
- color: 000000
  name: effort/minutes
- color: 000000
  name: effort/hours
- color: 000000
  name: effort/day
- color: 000000
  name: effort/days
- color: 000000
  name: effort/week
- color: 000000
  name: effort/weeks

###
### Impacts
###
- color: 000000
  name: impact/regression
- color: 000000
  name: impact/api-breakage
- color: 000000
  name: impact/quality
- color: 000000
  name: impact/dx
- color: 000000
  name: impact/test-flakiness

###
### Topics
###
- color: bf0f73
  name: topic/interoperability
- color: bf0f73
  name: topic/docs
- color: bf0f73
  name: topic/infra

###
### Priorities
###
- color: dd362a
  name: P0
- color: ce8048
  name: P1
- color: dbd81a
  name: P2
- color: 9fea8f
  name: P3

###
### Hints
###
- color: a5f7f3
  name: hint/good-first-issue
- color: a5f7f3
  name: hint/needs-contributor
- color: a5f7f3
  name: hint/needs-participation
- color: a5f7f3
  name: hint/needs-decision
- color: a5f7f3
  name: hint/needs-triage
- color: a5f7f3
  name: hint/needs-analysis
- color: a5f7f3
  name: hint/needs-author-input
- color: a5f7f3
  name: hint/needs-team-input
- color: a5f7f3
  name: hint/needs-community-input
- color: a5f7f3
  name: hint/needs-review
- color: a5f7f3
  name: hint/needs-help

###
### Statuses
###
- color: 000000
  name: status/done
- color: 000000
  name: status/deferred
- color: 000000
  name: status/in-progress
- color: 000000
  name: status/blocked
- color: 000000
  name: status/inactive
- color: 000000
  name: status/waiting
- color: 000000
  name: status/rotten
